### ISSUE TITLE
non-empty nifti files?

### ISSUE THREAD

**Issue by tyarkoni** [INCF/BIDS-examples#44]
@chrisfilo are you 100% against having datasets with non-empty nifti files? As you saw in incf/pybids#102, we do need actual images in order to test some things. They don't have to be very big--100 MB or so would probably do.

We could have a separate "BIDS-big-data" repo or something, but that seems a bit cluttered...

**Comment by tyarkoni** [comment]
On second thought, I'm closing this--I think it's important to keep this one lightweight. But let's organize a 2nd repo with actual data at Code Rodeo.

**Comment by satra** [comment]
@tyarkoni - just a thought - for various projects we are now using datalad to fetch necessary data at the time of testing. this keeps the repo lightweight and pulls in versioned data as necessary.

**Comment by yarikoptic** [comment]
Another alternative could be to include very downsampled nifti files. We did that in pymvpa before datalad rain: https://github.com/PyMVPA/PyMVPA/tree/master/mvpa2/data/haxby2001
We could have a utility to heavily downsample bids dataset while keeping it fully legit otherwise. Then it could even be included as is or via datalad to indeed avoid unneeded traffic.

**Comment by chrisfilo** [comment]
We use one in fmriprep tests https://osf.io/7zb25/

Best,
Chris
