### ISSUE TITLE
BIDS-iEEG | Where to put reconstructed surface data?

### ISSUE THREAD

**Issue by choldgraf** [INCF/BIDS-examples#57]
We've chatted a few times about the proper place for a surface reconstructions with BIDS-iEEG, and I feel like we should nail this down since @chrisfilo mentioned it in #55 and it'll be a really common component of BIDS-iEEG datasets. 

@dorahermes and I were thinking that for iEEG, surfaces are often the key anatomy data we have about a subject (e.g. visualizations are almost never done on volume data any more in ECoG). For that reason we thought they'd go into the main data directory structure, and not in a folder like `derivatives/`.

However, as @chrisfilo mentions this breaks convention with the rest of the BIDS world. Especially if the goal is to eventually merge the iEEG spec into the core BIDS specification, I think we probably need to put the surfaces in `derivatives/` to avoid confusion. @dorahermes what do you think? And does this sound correct @chrisfilo ?

_Note: I'm not sure where is the best place to put this question, as we've gone over it a bit in the google doc but I'm worried this isn't a very discoverable place to keep that conversation over time (so feel free to close this issue if people want to nail this down there)_

**Comment by chrisfilo** [comment]
I had a chat with @dorahermes about this. Here are some thoughts:

- I feel that it would be best to keep this consistent with the upcoming Structural preprocessing derivatives extension (see https://docs.google.com/document/d/1YG2g4UkEio4t_STIBOqYOwneLEs1emHIXbGKynx7V0Y/edit#heading=h.nlimrxs2jqsc). This would mean prescribing a path such as `/derivatives/<pipeline_name>/sub-<participant_label>/anat/<source_file>_[smoothwm|pial|midthickness|inflated][.L|.R].surf.gii`

- It's worth noting that since BIDS iEEG specifies the path to the surface file in the JSON file it is not strictly required to prescribe where surface files should be stored. This means that we can postpone this discussion until BIDS Derivatives matures a bit. 

- We also discussed that the validator should check if either T1w or surface is present. This could be implemented with some conditional logic.

As for where to post such questions. The [mailing list](https://groups.google.com/forum/#!forum/bids-discussion) is the best place to do this. With so many channels things can get confusing - I tried to make this a bit more clear on the website recently:
![image](https://user-images.githubusercontent.com/238759/36763478-01b1c63a-1bdd-11e8-9466-1b55f88f2171.png)

**Comment by choldgraf** [comment]
I'm +1 on punting on this for now, since as Chris mentions it's explicitly
required to provide a path to the relevant file anyway.
--

**Comment by dorahermes** [comment]
What does it mean to punt on something - to leave it for now or to make a decision?

**Comment by choldgraf** [comment]
hehe, sorry for the confusing language :-)  I meant "let's hold off on making a decision now, as it sounds like we don't *have* to make it now, and there will be more information to help us in making it later"

**Comment by choldgraf** [comment]
currently we're instructing people to put this in `derivatives/`, so I'm closing this for now unless a new development happens here
